/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddForm: typeof import('./src/components/AddForm.vue')['default']
    CardBook: typeof import('./src/components/CardBook.vue')['default']
    CardBookAdmin: typeof import('./src/components/CardBookAdmin.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Hero: typeof import('./src/components/Hero.vue')['default']
    IconBookmark: typeof import('./src/components/icons/IconBookmark.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    IMageEdit: typeof import('~icons/mage/edit')['default']
    IPhTrash: typeof import('~icons/ph/trash')['default']
    IRiArrowRightLine: typeof import('~icons/ri/arrow-right-line')['default']
    IRiBookmark3Line: typeof import('~icons/ri/bookmark3-line')['default']
    IRiHeartFill: typeof import('~icons/ri/heart-fill')['default']
    IRiListUnordered: typeof import('~icons/ri/list-unordered')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    Toast: typeof import('./src/components/Toast.vue')['default']
    UpdateForm: typeof import('./src/components/UpdateForm.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
